### ISSUE TITLE
Matlab Class Support

### ISSUE THREAD

**Issue by iandol** [JamesRitchie/language-matlab#12]
Hi, the TextMate bundle has recently been updated to support the Class syntax offered by MATLAB. It would be nice to pull that into Atom's MATLAB bundle.

**Comment by JamesRitchie** [comment]
Looks like #13 should have done it. Give it a test, and I'll release it in the next few days.

![matlab_syntax_highlighting](https://cloud.githubusercontent.com/assets/1486689/12246138/9f88831a-b8a4-11e5-95c0-16d426daa034.png)

**Comment by iandol** [comment]
Yes, this is working much better than before, thanks James!
