### ISSUE TITLE
Syntax highlighting: else, elseif

### ISSUE THREAD

**Issue by vargavince91** [JamesRitchie/language-matlab#17]
`else` and `elseif` doesn't get highlighted in atom:

Screenshot:
![matlabelse](https://cloud.githubusercontent.com/assets/9061239/13145608/18e28740-d652-11e5-9795-d79a2177faeb.png)

Code:
```matlab
if expression
    a=1
elseif expression
    a=2
else
    a=b
end
```

**Comment by tomrijndorp** [comment]
On a related note, it seems that the same is true for `case` in `switch` statements.

Screenshot:
![screen shot 2016-03-22 at 16 11 29](https://cloud.githubusercontent.com/assets/15803419/13956411/ea4cb6f6-f048-11e5-9ae0-673503fbb42b.png)

Code:

    switch myVar
    case 1
        doSomething();
    case 2
        doSomethingElse();
    end
